### ISSUE TITLE
Exit with signal 255

### ISSUE THREAD

**Issue by jhaiduce** [kmkolasinski/AwesomeBump#21] opened 2015-03-05 00:43 UTC
I'm on Fedora 21. I can build AwesomeBump but the executable does nothing and returns signal 255.

**Comment by kmkolasinski** [comment] 2015-03-05 08:17
What is written in log.txt file?

**Comment by jhaiduce** [comment] 2015-03-05 12:37
[04/03/2015 20:07:59] {Debug}            Starting application:
[04/03/2015 20:07:59] {Debug}            Widget OpenGL:  3 . 0
[04/03/2015 20:07:59] {Debug}            Context valid:  true
[04/03/2015 20:07:59] {Debug}            OpenGL information: 
[04/03/2015 20:07:59] {Debug}            VENDOR:  Intel Open Source Technology Center
[04/03/2015 20:07:59] {Debug}            RENDERER:  Mesa DRI Intel(R) Haswell Mobile 
[04/03/2015 20:07:59] {Debug}            VERSION:  3.0 Mesa 10.4.3
[04/03/2015 20:07:59] {Debug}            GLSL VERSION:  1.30
[04/03/2015 20:07:59] {Debug}            OpenGLVersionFlags():  QFlags()
[04/03/2015 20:07:59] {Debug}            GL 3.2 Not supported

**Comment by kmkolasinski** [comment] 2015-03-05 12:41
The problem is that your system is using openGL 3.0 but AB requires at least 4.0 version.

**Comment by jhaiduce** [comment] 2015-03-05 12:55
Ok, thanks! Apparently OpenGL 4.0 support is not available on Linux for my hardware (Intel Haswell video card). It runs on my Debian system which has nvidia though.

**Comment by kmkolasinski** [comment] 2015-03-05 16:55
Ok, good. Can we close this issue?

**Comment by patlecat** [comment] 2015-03-06 09:23
I have a similar issue under Windows 8.1-64 compiled with Qt 5.4.1. The program doesn't even start, no errors at all. Here is the log.txt:

```
[06/03/2015 10:14:05] {Debug} 		 Starting application:
[06/03/2015 10:14:05] {Debug} 		 Widget OpenGL:  4 . 3
[06/03/2015 10:14:05] {Debug} 		 Context valid:  true
[06/03/2015 10:14:05] {Debug} 		 OpenGL information: 
[06/03/2015 10:14:05] {Debug} 		 VENDOR:  Intel
[06/03/2015 10:14:05] {Debug} 		 RENDERER:  Intel(R) HD Graphics 4600
[06/03/2015 10:14:05] {Debug} 		 VERSION:  4.3.0 - Build 10.18.10.3995
[06/03/2015 10:14:05] {Debug} 		 GLSL VERSION:  4.30 - Build 10.18.10.3995
[06/03/2015 10:14:05] {Debug} 		 OpenGLVersionFlags():  QFlags()
[06/03/2015 10:14:05] {Debug} 		 Reading the list of available configs settings: ()
[06/03/2015 10:14:05] {Debug} 		 Supported GUI styles:  "Windows, WindowsXP, WindowsVista, Fusion"
[06/03/2015 10:14:05] {Debug} 		 Calling void __cdecl MainWindow::loadSettings(void)  loading from  "config.ini"
[06/03/2015 10:14:05] {Debug} 		 void __cdecl FBOImageProporties::init(class QImage &)
[06/03/2015 10:14:05] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 2
[06/03/2015 10:14:05] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 3
[06/03/2015 10:14:05] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 4
[06/03/2015 10:14:05] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 5
[06/03/2015 10:14:05] {Debug} 		 void __cdecl FBOImageProporties::init(class QImage &)
[06/03/2015 10:14:05] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 7
[06/03/2015 10:14:05] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 8
[06/03/2015 10:14:05] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 9
[06/03/2015 10:14:05] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 10
[06/03/2015 10:14:05] {Debug} 		 void __cdecl FBOImageProporties::init(class QImage &)
[06/03/2015 10:14:05] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 12
[06/03/2015 10:14:05] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 13
[06/03/2015 10:14:05] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 14
[06/03/2015 10:14:05] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 15
[06/03/2015 10:14:06] {Debug} 		 void __cdecl FBOImageProporties::init(class QImage &)
[06/03/2015 10:14:06] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 17
[06/03/2015 10:14:06] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 18
[06/03/2015 10:14:06] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 19
[06/03/2015 10:14:06] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 20
[06/03/2015 10:14:06] {Debug} 		 void __cdecl FBOImageProporties::init(class QImage &)
[06/03/2015 10:14:06] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 22
[06/03/2015 10:14:06] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 23
[06/03/2015 10:14:06] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 24
[06/03/2015 10:14:06] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 25
[06/03/2015 10:14:06] {Debug} 		 calling  void __cdecl MainWindow::resizeEvent(class QResizeEvent *)
[06/03/2015 10:14:06] {Debug} 		 Loading quad (vertex shader)
[06/03/2015 10:14:06] {Debug} 		 done
[06/03/2015 10:14:06] {Debug} 		 Loading quad (fragment shader)
[06/03/2015 10:14:06] {Debug} 		 done
[06/03/2015 10:14:06] {Debug} 		 Loading quad (tessellation control shader)
[06/03/2015 10:14:06] {Debug} 		 done
[06/03/2015 10:14:06] {Debug} 		 Loading quad (tessellation evaluation shader)
[06/03/2015 10:14:06] {Debug} 		 done
[06/03/2015 10:14:06] {Debug} 		 Loading quad (geometry shader)
[06/03/2015 10:14:06] {Debug} 		 done
[06/03/2015 10:14:06] {Debug} 		 __cdecl Mesh::Mesh(class QString,class QString) Loading new mesh: "models/Cube.obj"
[06/03/2015 10:14:06] {Debug} 		 __cdecl Mesh::Mesh(class QString,class QString) Loading mesh file failed: "models/Cube.obj"
[06/03/2015 10:14:06] {Debug} 		 calling  void __cdecl GLImage::initializeGL(void)
[06/03/2015 10:14:06] {Debug} 		 Loading filters (fragment shader)
[06/03/2015 10:14:06] {Debug} 		 done
[06/03/2015 10:14:06] {Debug} 		 Loading filters (vertex shader)
[06/03/2015 10:14:06] {Debug} 		 done

```

**Comment by patlecat** [comment] 2015-03-06 09:27
_...follow up_: I started the program with the discrete nVidia GPU this time and suddenly it runs! But why would you exclude the intel built-in GPU? Are you sure it can't be used for AwesomeBump??

**Log.txt**
```
[06/03/2015 10:25:09] {Debug} 		 Starting application:
[06/03/2015 10:25:10] {Debug} 		 Widget OpenGL:  4 . 5
[06/03/2015 10:25:10] {Debug} 		 Context valid:  true
[06/03/2015 10:25:10] {Debug} 		 OpenGL information: 
[06/03/2015 10:25:10] {Debug} 		 VENDOR:  NVIDIA Corporation
[06/03/2015 10:25:10] {Debug} 		 RENDERER:  GeForce GTX 980M/PCIe/SSE2
[06/03/2015 10:25:10] {Debug} 		 VERSION:  4.5.0 NVIDIA 347.52
[06/03/2015 10:25:10] {Debug} 		 GLSL VERSION:  4.50 NVIDIA
[06/03/2015 10:25:10] {Debug} 		 OpenGLVersionFlags():  QFlags()
[06/03/2015 10:25:10] {Debug} 		 Reading the list of available configs settings: ()
[06/03/2015 10:25:10] {Debug} 		 Supported GUI styles:  "Windows, WindowsXP, WindowsVista, Fusion"
[06/03/2015 10:25:10] {Debug} 		 Calling void __cdecl MainWindow::loadSettings(void)  loading from  "config.ini"
[06/03/2015 10:25:10] {Debug} 		 void __cdecl FBOImageProporties::init(class QImage &)
[06/03/2015 10:25:10] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 2
[06/03/2015 10:25:10] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 3
[06/03/2015 10:25:10] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 4
[06/03/2015 10:25:10] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 5
[06/03/2015 10:25:10] {Debug} 		 void __cdecl FBOImageProporties::init(class QImage &)
[06/03/2015 10:25:10] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 7
[06/03/2015 10:25:10] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 8
[06/03/2015 10:25:10] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 9
[06/03/2015 10:25:10] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 10
[06/03/2015 10:25:10] {Debug} 		 void __cdecl FBOImageProporties::init(class QImage &)
[06/03/2015 10:25:10] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 12
[06/03/2015 10:25:10] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 13
[06/03/2015 10:25:10] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 14
[06/03/2015 10:25:10] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 15
[06/03/2015 10:25:10] {Debug} 		 void __cdecl FBOImageProporties::init(class QImage &)
[06/03/2015 10:25:10] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 17
[06/03/2015 10:25:10] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 18
[06/03/2015 10:25:10] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 19
[06/03/2015 10:25:10] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 20
[06/03/2015 10:25:10] {Debug} 		 void __cdecl FBOImageProporties::init(class QImage &)
[06/03/2015 10:25:10] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 22
[06/03/2015 10:25:10] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 23
[06/03/2015 10:25:10] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 24
[06/03/2015 10:25:10] {Debug} 		 FBOImages::creating new FBO( 512 , 512 ) with id= 25
[06/03/2015 10:25:10] {Debug} 		 calling  void __cdecl MainWindow::resizeEvent(class QResizeEvent *)
[06/03/2015 10:25:10] {Debug} 		 Loading quad (vertex shader)
[06/03/2015 10:25:10] {Debug} 		 done
[06/03/2015 10:25:10] {Debug} 		 Loading quad (fragment shader)
[06/03/2015 10:25:10] {Debug} 		 done
[06/03/2015 10:25:10] {Debug} 		 Loading quad (tessellation control shader)
[06/03/2015 10:25:10] {Debug} 		 done
[06/03/2015 10:25:10] {Debug} 		 Loading quad (tessellation evaluation shader)
[06/03/2015 10:25:10] {Debug} 		 done
[06/03/2015 10:25:10] {Debug} 		 Loading quad (geometry shader)
[06/03/2015 10:25:10] {Debug} 		 done
[06/03/2015 10:25:10] {Debug} 		 __cdecl Mesh::Mesh(class QString,class QString) Loading new mesh: "models/Cube.obj"
[06/03/2015 10:25:10] {Debug} 		 __cdecl Mesh::Mesh(class QString,class QString) Loading mesh file failed: "models/Cube.obj"
[06/03/2015 10:25:10] {Debug} 		 calling  void __cdecl GLImage::initializeGL(void)
[06/03/2015 10:25:10] {Debug} 		 Loading filters (fragment shader)
[06/03/2015 10:25:10] {Debug} 		 done
[06/03/2015 10:25:10] {Debug} 		 Loading filters (vertex shader)
[06/03/2015 10:25:10] {Debug} 		 done
[06/03/2015 10:25:10] {Debug} 		 calling void __cdecl MainWindow::showEvent(class QShowEvent *)
[06/03/2015 10:25:10] {Debug} 		 Doing first draw of "diffuse"  texture.
[06/03/2015 10:25:10] {Debug} 		 MainWindow::Initialization
[06/03/2015 10:25:10] {Warning} 	 QWidget::repaint: Recursive repaint detected
[06/03/2015 10:25:10] {Debug} 		 Doing first draw of "specular"  texture.
[06/03/2015 10:25:10] {Debug} 		 Doing first draw of "height"  texture.
[06/03/2015 10:25:10] {Debug} 		 Doing first draw of "normal"  texture.
[06/03/2015 10:25:11] {Debug} 		 Doing first draw of "occlusion"  texture.
[06/03/2015 10:25:15] {Debug} 		 calling  void __cdecl MainWindow::resizeEvent(class QResizeEvent *)
[06/03/2015 10:25:15] {Debug} 		 calling  void __cdecl MainWindow::resizeEvent(class QResizeEvent *)
[06/03/2015 10:25:15] {Debug} 		 calling  void __cdecl MainWindow::resizeEvent(class QResizeEvent *)
[06/03/2015 10:25:23] {Debug} 		 calling void __cdecl MainWindow::closeEvent(class QCloseEvent *)
[06/03/2015 10:25:23] {Debug} 		 Removing settings tool.
[06/03/2015 10:25:23] {Debug} 		 __cdecl FBOImageProporties::~FBOImageProporties(void)
[06/03/2015 10:25:23] {Debug} 		 __cdecl FBOImageProporties::~FBOImageProporties(void)
[06/03/2015 10:25:23] {Debug} 		 __cdecl FBOImageProporties::~FBOImageProporties(void)
[06/03/2015 10:25:23] {Debug} 		 __cdecl FBOImageProporties::~FBOImageProporties(void)
[06/03/2015 10:25:23] {Debug} 		 __cdecl FBOImageProporties::~FBOImageProporties(void)
[06/03/2015 10:25:23] {Debug} 		 __cdecl Mesh::~Mesh(void)  destroying mesh: "Cube.obj"

```

**Comment by kmkolasinski** [comment] 2015-03-06 09:35
Hi,
Intel(R) HD Graphics - even if there is written that it is openGL 4.3 I would not believe it (e.g. some features may not be supported or even emulated). This is my experience with intel cards.

**Comment by jhaiduce** [comment] 2015-03-06 13:07
As far as I'm concerned you can close it. 

Of course I'd like it to work on my OpenGL 3.x hardware but if you don't plan to support such hardware then there's no point in leaving the issue open. I might suggest you add something to write an error message to the screen so it doesn't just fail silently though; that way you won't get people like me constantly opening bug reports about it.

**Comment by kmkolasinski** [comment] 2015-03-06 13:29
Ok, thank you for the advice - actually this is a really good idea. I will think about this in new releases.
 
Supporting openGL is really hard at this stage of AB, at least for one person, but... AB is an open source anyone can contribute to this project and make it better.  I accept any kind of help.
Best,
K

**Comment by patlecat** [comment] 2015-03-07 15:21
I support that, always tell users why you don't support something *before* you close the app. This way it won't look like a bug or crash ;)

**Comment by kmkolasinski** [comment] 2015-03-07 15:27
Sorry I ment to write "Supporting openGL version 3.3". I will keep your advice in mind :)
I really like this joke: http://thegeekwhisperer.com/2009/09/24/bug-vs-feature/

**Closed** 2015-03-24 14:01 UTC
