### ISSUE TITLE
3D viewport navigation lags back to origin

### ISSUE THREAD

**Issue by nevr2k** [kmkolasinski/AwesomeBump#33] opened 2015-04-04 09:21 UTC
Hey Krzysztof,

i am running arch (kernel 3.19.2) and have some issues using the current AB master:

- the compile produces warnings (qt 5.4.1)
- the program runs but 3d viewport navigation is not working (lags back to starting location when trying to navigate)
- used command line and also tried qtcreator folowing the build pdf

./linuxBuildScript.sh 
WARNING: target.path is not defined: install target not created
mainwindow.ui: Warning: The name 'layoutWidget' (QWidget) is already in use, defaulting to 'layoutWidget1'.

glwidget.cpp:708:11: warning: enumeration value ‘MAX_TEXTURES_TYPE’ not handled in switch [-Wswitch]
     switch(tType){
           ^
mainwindow.cpp:996:35: warning: unused parameter ‘size’ [-Wunused-parameter]
 void MainWindow::changeWidth (int size){
                                   ^
mainwindow.cpp:1002:35: warning: unused parameter ‘size’ [-Wunused-parameter]
 void MainWindow::changeHeight(int size){
                                   ^
mainwindow.cpp:1189:48: warning: unused parameter ‘indeks’ [-Wunused-parameter]
 void MainWindow::updatePerformanceSettings(int indeks){
                                                ^
mainwindow.cpp:1632:38: warning: unused parameter ‘index’ [-Wunused-parameter]
 void MainWindow::setOutputFormat(int index){
                                      ^
utils/Mesh.cpp:109:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(unsigned int i = 0 ; i < gl_vertices.size() ; i++ ){
                                ^
utils/Mesh.cpp:152:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for( int k = 0 ; k < verlet[i].size() ; k++){
                            ^
utils/Mesh.cpp:155:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for( int l = 0 ; l < verlet[i].size() ; l++){
                                ^
utils/Mesh.cpp:342:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (unsigned int a = 0; a < vertexCount/3; a++)
                                ^
utils/Mesh.cpp:387:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (unsigned int a = 0; a < vertexCount; a++)
                                ^
formsettingsfield.cpp:117:45: warning: unused parameter ‘text’ [-Wunused-parameter]
 void FormSettingsField::nameChanged(QString text){
                                             ^
formsettingscontainer.cpp:72:63: warning: unused parameter ‘field’ [-Wunused-parameter]
 void FormSettingsContainer::reloadSettings(FormSettingsField* field){
                                                               ^
utils/qglbuffers.cpp:373:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(unsigned int i = 0;i< attachments.size();i++){
                             ^

**Comment by kmkolasinski** [comment] 2015-04-07 21:09
Hi, I was on holidays. Can you check older versions of AB? 
I've added the "mouse loop" feature recently which I think does the problem in your case.

**Comment by nevr2k** [comment] 2015-04-08 15:48
Hey there, np thanks for the follow up.

i tried 2.1 but i cant get it compiled - getting an error

/usr/lib/qt/bin/rcc -name content ../content.qrc -o qrc_content.cpp
Makefile:597: recipe for target 'qrc_content.cpp' failed
RCC: Error in '../content.qrc': Cannot find file 'content/Capsule.obj'
make: *** [qrc_content.cpp] Error 1
17:44:55: The process "/usr/bin/make" exited with code 2.

**Comment by kmkolasinski** [comment] 2015-04-08 16:04
Ok, I know where is the problem. 
Please remove the Capsule.obj file from the content.qrc file.
You can do it through the Qt creator or just by opening this file 
in any text editor and remove the line:
<file>content/Capsule.obj</file>

**Comment by Robert42** [comment] 2015-04-09 22:51
Hey, I also have the 3d viewport navigation problems.

I think, there are two different problems. The error described in this issue (the navigation lags back to origin) occures the first time in the commit be8bb6f74a4bd492ca471b92f5b97f3ebe01dd6c (I have used `git bisect`)

But I had a second issue, that the viewport lags for one or two seconds. That issue is already reproducable in 2.x versions.

**Comment by kmkolasinski** [comment] 2015-04-10 06:27
Ok, thanks for info. I'm waiting for P-R.

**Comment by Robert42** [comment] 2015-04-10 12:34
Ok, my Pull Request is online. But I don't like it, because it's somehow ugly. You can use if you want. Maybe you just want to look at it and develop a better solution.

**Comment by kmkolasinski** [comment] 2015-04-10 12:52
Ok, thanks. Yeah its a really big pull request. 
Can you try something simpler before I do your pull request? 
You can disable all image processings during the mouse dragging:

You need to add one new variable: e.g: bool bMouseDragging; in class GLImage.
In cpp file you can find such line:
if(!bSkipStandardProcessing){
change it to something like that:
if(!bSkipStandardProcessing && !bMouseDragging){
then in function:
void GLImage::mousePressEvent(QMouseEvent *event)
add line:
bMouseDragging = true;
and in:
void GLImage::mouseReleaseEvent(QMouseEvent *event){
add line:
bMouseDragging = false;
and updateGL() at the end.

What about that?  I know that you will lost all image effects during mouse dragging, but such solution is much simpler.

**Comment by Robert42** [comment] 2015-04-10 13:05
Ok, I've tried the bMouseDragging trick, but I couldn't see a difference between "before" and "after" using bMouseDragging to controll the image effects

**Comment by kmkolasinski** [comment] 2015-04-10 13:10
Ok thank, I was courious, because It should help to reduce the GPU computation time, but if the problem is in drivers as you wrote, your solutions will be better. I will take a look at your PR this evening.

**Comment by kmkolasinski** [comment] 2015-04-10 17:15
Ok, I did the merge. Once again thanks for this fix, I see improvement! 
Can you check new commit just in case? If everything will be ok, you can close this issue.

**Comment by Robert42** [comment] 2015-04-10 17:26
You're welcome :)
I've checked, and it looks ok for me.

**Comment by nevr2k** [comment] 2015-04-12 07:25
i will give it a try with this improvement.
fixing and using the 2.1 compile by removing Capsule.obj is not an option for me

**Comment by kmkolasinski** [comment] 2015-04-12 07:28
Ok, please give me a feedback if it works now.

**Comment by nevr2k** [comment] 2015-04-12 07:49
works flawlessly.

thanks a lot from my side Robert for the PR and Krzysztof for PR check implement and of curse making and maintaining AB : -)

**Comment by kmkolasinski** [comment] 2015-04-23 19:43
Ok, I'm closing this issue.

**Closed by kmkolasinski** 2015-04-23 19:43 UTC
