### ISSUE TITLE
The website is going down in 2 weeks

### ISSUE THREAD

**Issue by OBKF** [kmkolasinski/AwesomeBump#145] opened 2018-10-18 10:29 UTC
![image](https://user-images.githubusercontent.com/12987951/47148601-05a8ad00-d2c9-11e8-9b4e-f2c52dd1fbde.png)

**Comment by Calinou** [comment] 2018-10-18 12:38
The website could be migrated to [GitHub Pages](https://pages.github.com/), but that will require some manual work if the current site isn't based on a static site generator.

**Comment by kmkolasinski** [comment] 2018-10-22 08:55
Hi, thanks for information, but I think the current github page is enough.

**Comment by OBKF** [comment] 2018-10-23 08:07
I got there from a post in Blender nation's website so I thought that someone should notify the devs to update the links or what ever, github pages are fine for the most part.

**Comment by kmkolasinski** [comment] 2018-10-23 08:37
I will try to do something with this. Thanks again for feedback

**Comment by OBKF** [comment] 2018-10-23 09:09
I am glad I can help, this is a cool tool.

_Ps: As a side note can we have an OpenGL3.0 version? for some reason my intelHD 4600 supports OpenGL4.3 on windows and 3.0 on Linux, and this is common for all intel integrated GPUs. (so I have to dual boot to use this tool 😢 )_

**Comment by Calinou** [comment] 2018-10-23 09:11
> for some reason my intelHD 4600 supports OpenGL4.3 on windows and 3.0 on Linux, and this is common for all intel integrated GPUs.

This is likely because AwesomeBump requests a compatibility OpenGL context instead of a core context, and compatibility contexts are limited to OpenGL 3.0 on Mesa drivers (except RadeonSI as of recently).

**Comment by OBKF** [comment] 2018-10-23 09:14
It's sad to hear it, anyways dualboot is the solution for now.

**Comment by kmkolasinski** [comment] 2018-10-23 10:08
Not, really. Few weeks ago I put some efforts to switch AB to core compatibility, here is the branch: 
https://github.com/kmkolasinski/AwesomeBump/tree/switch_to_core_profile

You can try this, but you have to build AB from source.

**Comment by OBKF** [comment] 2018-10-23 11:24
Ok thanks, I will try this later.

**Comment by kmkolasinski** [comment] 2019-09-10 14:55
AB Release branch is now merged with Core profile support, this has been confirmed to solve openGL compatibility issues by few users. 
PS: I couldn't manage to migrate old website :/

**Closed as completed by kmkolasinski** 2019-09-10 14:55 UTC
