### ISSUE TITLE
how2: Multiply Diffuse Map with a ColorVal - where to start?

### ISSUE THREAD

**Issue by daxbo** [kmkolasinski/AwesomeBump#86] opened 2016-03-25 18:02 UTC
Hello, not sure if that is the right place to ask for help - if not please tell me where I can post questions like that.
Can someone expreienced please tell me where I need to add code snipets to add a color multiply calculation?
I guess i need to tweak the plane shader?
Or would it be better to add the color to the final diffuse map?
any help would be greatly appreciated

regards

**Comment by kmkolasinski** [comment] 2016-04-20 17:47
I don't know why but I somehow did not notice your issue, sorry for that. Is your question still current?

**Comment by daxbo** [comment] 2016-04-28 08:35
hi , yeah thanks. I already changed the code... just editing the invert option to mutiply a color of my choice. Thank.

**Comment by kmkolasinski** [comment] 2016-04-28 08:36
Great, thanks for info. If the issue is solved for you you can close it.

**Closed** 2016-04-28 08:41 UTC
