### ISSUE TITLE
Odd normal map display in viewport

### ISSUE THREAD

**Issue by Terrance8D** [kmkolasinski/AwesomeBump#39] opened 2015-05-16 20:20 UTC
Ever since I upgraded to AB Pi, I've noticed that the display of normal maps is very different from previous versions. Even without the compositing turned on (Glow, DOF) my maps display like this:
![screenshot from 2015-05-16 13 11 19](https://cloud.githubusercontent.com/assets/11653287/7667813/1dd414a8-fbce-11e4-9764-a5cce89518f6.jpg)
What would be causing this issue?

**Comment by kmkolasinski** [comment] 2015-05-17 08:52
Could you be more precise? I don't know what is your problem? For me on this screenshot everything is ok.

**Comment by Terrance8D** [comment] 2015-05-17 17:32
Here's a screenshot of the same texture in AB 3.0:
![screenshot from 2015-05-17 10 27 45](https://cloud.githubusercontent.com/assets/11653287/7671325/b49169ca-fc7f-11e4-8122-19deda5e8bb3.jpg)
Is this just a change in the rendering code?

**Comment by kmkolasinski** [comment] 2015-05-17 17:37
Yeah, I changed a bit in code, so that maybe that is the problem. Today (in few hours) I will release new version of AB4.0. Could you check it for me and send me some feedback?

**Comment by Terrance8D** [comment] 2015-05-17 19:14
I just built 4.0 beta (thanks again for the build script!), and it's working fine so far. Well, I made the mistake of turning the light settings up to maximum before I switched to bump map shading and got flared to death, but that's my fault.:P I'm getting some strange issues with this though, here's how normal maps display now:
![screenshot from 2015-05-17 12 06 41](https://cloud.githubusercontent.com/assets/11653287/7671643/b0b9049e-fc8d-11e4-975d-8eb9fa76a37c.png)
Even more strange, when I go to the grunge texture settings and click "enable normalization", the normal texture displays as expected. Then if I go back to the diffuse settings I see the diffuse texture displayed on my object - with enable preview turned on!

**Comment by kmkolasinski** [comment] 2015-05-17 20:21
1) Yeah, I think normal map is OK in the image you send me, this is because I decided to remove this old annoying blue preview in the 3D widget when "Conversion from Basemap" was enabled. So from now it will be grayscale image only.
2) New video with 4.0 is ready at YT, so you can watch it to see how to use Grunge maps in AB.
3) If you will have still problems, could you be so kind and make a short movie and send me in order to see how to reproduce the bug you found?

**Comment by kmkolasinski** [comment] 2015-05-17 20:24
Ah OK, I see the problem, thanks! Fortunately this is really small bug :)

**Comment by Terrance8D** [comment] 2015-05-17 20:37
Yes, I'll make sure to do that in the future.:)

**Comment by kmkolasinski** [comment] 2015-06-18 19:17
Closing this issue.

**Closed by kmkolasinski** 2015-06-18 19:17 UTC
